site_name: "Sistema de Gestión Hirata Transporte"
repo_url: "https://github.com/lilithrv/hirata-transporte"
repo_name: "hirata-transporte"
theme:
  name: material
  language: es
  palette:
    primary: red  # Color institucional o llamativo para transporte
    accent: red
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.footer
  palette:
    # Configuración del Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    # Configuración del Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
        
copyright: "&copy; 2026 Empresa de Transporte Hirata — Todos los derechos reservados."        


plugins:
  - search


markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


docs_dir: docs

nav:
  - Portal de Inicio: index.md
  - Manual Técnico (Desarrolladores):
      - Arquitectura y Stack: tecnico/arquitectura.md
      - Modelo de Base de Datos: tecnico/base-datos.md
  - Manual de Usuario (Operadores):
      - Registro de Mantenimiento: usuario/mantenimiento.md
      - Control de Inventario: usuario/inventario.md
