
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# CONFIGURACION DE BASE DE DATOS - PROYECTO HIRATA
db.host=localhost
db.port=3306
db.user=root
db.pass=root

# Nombres de los esquemas
db.name=transporte_hirata
db.test_name=mantenimiento_test