
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# CONFIGURACION DE BASE DE DATOS - PROYECTO HIRATA
db.host=186.64.123.120
db.port=3306
db.user=usuario001
db.pass=usuario001pass

# Nombres de los esquemas
db.name=hirata_001_db
db.test_name=mantenimiento_test
