/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.historialequipos;

import dao.EquipoOficinaDAO;
import dao.TipoEquipoDAO;
import dao.UsuarioDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import modelo.EquipoOficina;
import modelo.TipoEquipo;
import modelo.Usuario;

/**
 *
 * @author leslie
 */
public class DialogNuevoEquipo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoEquipo.class.getName());
    private boolean confirmado = false;
    private TipoEquipoDAO tipoDAO;
    private List<TipoEquipo> listaTipos = new ArrayList<>();
    private EquipoOficinaDAO equipoDAO;
    private UsuarioDAO usuarioDAO;
    private List<Usuario> listaResponsables = new ArrayList<>();

    /**
     * Creates new form DialogNuevoEquipo
     */
    public DialogNuevoEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);

        // Configurar el spinner como fecha
        SpinnerDateModel dateModel = new SpinnerDateModel();
        spinnerFecha.setModel(dateModel);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editor);

        tipoDAO = new TipoEquipoDAO();
        equipoDAO = new EquipoOficinaDAO();
        usuarioDAO = new UsuarioDAO();

        cargarComboTipo();
        cargarComboEstado();
        cargarComboResponsable();
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    private void cargarComboTipo() {
        TipoEquipoDAO tipoDAO = new TipoEquipoDAO();
        listaTipos = tipoDAO.listarTodos();
        cmbTipo.removeAllItems();
        cmbTipo.addItem("Seleccionar");
        for (TipoEquipo t : listaTipos) {
            cmbTipo.addItem(t.getNombre());
        }
    }

    private void cargarComboEstado() {
        cmbEstado.removeAllItems();
        cmbEstado.addItem("Seleccionar");
        cmbEstado.addItem("Activo");
        cmbEstado.addItem("Inactivo");
        cmbEstado.addItem("En Mantenimiento");
    }

    private void cargarComboResponsable() {
        UsuarioDAO dao = new UsuarioDAO();
        listaResponsables = dao.listarResponsablesEquipo();
        cmbResponsable.removeAllItems();
        cmbResponsable.addItem("Sin asignar");
        for (Usuario u : listaResponsables) {
            cmbResponsable.addItem(u.getNombreUsuario());
        }
    }

    private void limpiarFormulario() {
        cmbTipo.setSelectedIndex(0);
        txtMarca.setText("");
        txtModelo.setText("");
        txtSerie.setText("");
        cmbEstado.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        lblSerie = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblResponsable = new javax.swing.JLabel();
        cmbResponsable = new javax.swing.JComboBox<>();
        spinnerFecha = new javax.swing.JSpinner();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR EQUIPO");

        lblTipo.setText("TIPO EQUIPO");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMarca.setText("MARCA");

        lblModelo.setText("MODELO");

        lblSerie.setText("N° SERIE");

        lblEstado.setText("ESTADO");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblResponsable.setText("RESPONSABLE");

        cmbResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFecha.setText("FECHA ADQUISICIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(lblTipo)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblResponsable)
                            .addComponent(lblSerie)
                            .addComponent(lblFecha))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerFecha)
                            .addComponent(txtMarca)
                            .addComponent(cmbTipo, 0, 273, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtSerie)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(41, 41, 41)
                .addComponent(btnAgregar)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipo)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerie))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResponsable)
                    .addComponent(cmbResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAgregar))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // ── Validaciones ──────────────────────────────────────────
        int indexTipo = cmbTipo.getSelectedIndex();
        if (indexTipo == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de equipo.");
            return;
        }
        TipoEquipo tipoSeleccionado = listaTipos.get(indexTipo - 1);

        String marca = txtMarca.getText().trim();
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la marca.");
            return;
        }
        String modelo = txtModelo.getText().trim();
        if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el modelo.");
            return;
        }
        String serie = txtSerie.getText().trim();
        if (serie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de serie.");
            return;
        }
        String estado = (String) cmbEstado.getSelectedItem();
        if (estado == null || estado.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione un estado.");
            return;
        }

        // ── Responsable (opcional) ────────────────────────────────
        int indexResp = cmbResponsable.getSelectedIndex();

        // ── Fecha adquisicion (opcional) ──────────────────────────
        Date fechaSeleccionada = (Date) spinnerFecha.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaAdquisicion = sdf.format(fechaSeleccionada);

        // ── Construir objeto ──────────────────────────────────────
        EquipoOficina equipo = new EquipoOficina();
        equipo.setTipoEquipo(tipoSeleccionado);
        equipo.setMarca(marca);
        equipo.setModelo(modelo);
        equipo.setNumeroSerie(serie);
        equipo.setEstado(estado);
        equipo.setFechaAdquisicion(fechaAdquisicion);

        // responsable es opcional, índice 0 = "Sin asignar"
        if (indexResp > 0) {
            equipo.setIdResponsable(listaResponsables.get(indexResp - 1).getIdUsuario());
        }

        // ── Guardar ───────────────────────────────────────────────
        EquipoOficinaDAO dao = new EquipoOficinaDAO();
        if (dao.insertar(equipo)) {
            JOptionPane.showMessageDialog(this, "Equipo registrado correctamente.");
            confirmado = true;
            dispose(); // cierra el dialog
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogNuevoEquipo dialog = new DialogNuevoEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbResponsable;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
