/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.historialequipos;

import vista.EstiloHirata;

import dao.EquipoOficinaDAO;
import dao.SoftwareDAO;
import dao.TipoEquipoDAO;
import dao.UsuarioDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import modelo.EquipoOficina;
import modelo.Software;
import modelo.TipoEquipo;
import modelo.Usuario;

/**
 *
 * @author leslie
 */
public class DialogEditarEquipo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogEditarEquipo.class.getName());
    private boolean confirmado = false;
    private EquipoOficina equipo;
    private EquipoOficinaDAO equipoDAO;
    private List<TipoEquipo> listaTipos = new ArrayList<>();
    private List<Usuario> listaResponsables = new ArrayList<>();
    private UsuarioDAO usuarioDAO;
    private TipoEquipoDAO tipoDAO;

    /**
     * Creates new form DialogEditarEquipo
     */
    public DialogEditarEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        EstiloHirata.aplicarDialogoOscuro(this);
    }

    DialogEditarEquipo(java.awt.Frame parent, boolean modal, EquipoOficina equipo) {
        super(parent, modal);
        initComponents();
        EstiloHirata.aplicarDialogoOscuro(this);

        this.setLocationRelativeTo(parent);

        this.equipo = equipo;

        tipoDAO = new TipoEquipoDAO();
        equipoDAO = new EquipoOficinaDAO();
        usuarioDAO = new UsuarioDAO();

        SpinnerDateModel dateModel = new SpinnerDateModel();
        spinnerFecha.setModel(dateModel);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editor);
        EstiloHirata.aplicarSpinnerOscuro(spinnerFecha);

        cargarComboTipo();
        cargarComboEstado();
        cargarComboResponsable();
        cargarDatos();
        EstiloHirata.aplicarSpinnerOscuro(spinnerFecha);

    }

    public boolean isConfirmado() {
        return confirmado;
    }

    private void cargarComboEstado() {
        cmbEstado.removeAllItems();
        cmbEstado.addItem("Seleccionar");
        cmbEstado.addItem("Activo");
        cmbEstado.addItem("Inactivo");
        cmbEstado.addItem("En Mantenimiento");
    }

    private void cargarComboTipo() {
        TipoEquipoDAO dao = new TipoEquipoDAO();
        listaTipos = dao.listarTodos();
        cmbTipo.removeAllItems();
        cmbTipo.addItem("Seleccionar");
        for (TipoEquipo t : listaTipos) {
            cmbTipo.addItem(t.getNombre());
        }
    }

    private void cargarComboResponsable() {
        UsuarioDAO dao = new UsuarioDAO();
        listaResponsables = dao.listarResponsablesEquipo();
        cmbResponsable.removeAllItems();
        cmbResponsable.addItem("Sin asignar");
        for (Usuario u : listaResponsables) {
            cmbResponsable.addItem(u.getNombreUsuario());
        }
    }

    private void cargarDatos() {
        // Seleccionar el tipo en el combo
        for (int i = 0; i < listaTipos.size(); i++) {
            if (listaTipos.get(i).getIdTipoEquipo() == equipo.getTipoEquipo().getIdTipoEquipo()) {
                cmbTipo.setSelectedIndex(i + 1); // +1 por el "Seleccionar"
                break;
            }
        }

        txtMarca.setText(equipo.getMarca());
        txtModelo.setText(equipo.getModelo());
        txtSerie.setText(equipo.getNumeroSerie());
        cmbEstado.setSelectedItem(equipo.getEstado());

        // Responsable
        for (int i = 0; i < listaResponsables.size(); i++) {
            if (listaResponsables.get(i).getIdUsuario() == equipo.getIdResponsable()) {
                cmbResponsable.setSelectedIndex(i + 1); // +1 por el "Sin asignar"
                break;
            }
        }

        // Fecha adquisicion
        if (equipo.getFechaAdquisicion() != null && !equipo.getFechaAdquisicion().isEmpty()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date fecha = sdf.parse(equipo.getFechaAdquisicion());
                spinnerFecha.setValue(fecha);
            } catch (ParseException e) {
                System.err.println("Error al cargar fecha: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblResponsable = new javax.swing.JLabel();
        cmbResponsable = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        spinnerFecha = new javax.swing.JSpinner();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitulo.setText("EDITAR EQUIPO");

        lblTipo.setText("TIPO EQUIPO");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMarca.setText("MARCA");

        lblModelo.setText("MODELO");

        lblSerie.setText("N° SERIE");

        lblEstado.setText("ESTADO");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblResponsable.setText("RESPONSABLE");

        cmbResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFecha.setText("FECHA ADQUISICIÓN");

        btnCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCancelar.setText("CANCELAR");

        btnEditar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinnerFecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblSerie)
                            .addComponent(lblEstado)
                            .addComponent(lblResponsable))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTipo, 0, 285, Short.MAX_VALUE)
                            .addComponent(txtSerie)
                            .addComponent(cmbResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResponsable))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        // ── Validaciones ──────────────────────────────────────────
        int indexTipo = cmbTipo.getSelectedIndex();
        if (indexTipo == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de equipo.");
            return;
        }
        TipoEquipo tipoSeleccionado = listaTipos.get(indexTipo - 1);

        String marca = txtMarca.getText().trim();
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la marca.");
            return;
        }
        String modelo = txtModelo.getText().trim();
        if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el modelo.");
            return;
        }
        String serie = txtSerie.getText().trim();
        if (serie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de serie.");
            return;
        }
        String estado = (String) cmbEstado.getSelectedItem();
        if (estado == null || estado.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione un estado.");
            return;
        }

        // ── Responsable (opcional) ────────────────────────────────
        int indexResp = cmbResponsable.getSelectedIndex();

        // ── Fecha adquisicion ─────────────────────────────────────
        Date fechaSeleccionada = (Date) spinnerFecha.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaAdquisicion = sdf.format(fechaSeleccionada);

        // ── Construir objeto con el mismo ID ──────────────────────
        equipo.setTipoEquipo(tipoSeleccionado);
        equipo.setMarca(marca);
        equipo.setModelo(modelo);
        equipo.setNumeroSerie(serie);
        equipo.setEstado(estado);
        equipo.setFechaAdquisicion(fechaAdquisicion);

        if (indexResp > 0) {
            equipo.setIdResponsable(listaResponsables.get(indexResp - 1).getIdUsuario());
        } else {
            equipo.setIdResponsable(0); // sin asignar
        }

        // ── Actualizar ────────────────────────────────────────────
        EquipoOficinaDAO dao = new EquipoOficinaDAO();
        if (dao.actualizar(equipo)) {
            JOptionPane.showMessageDialog(this, "Equipo actualizado correctamente.");
            confirmado = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar. Verifique que el N° de serie no esté repetido.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogEditarEquipo dialog = new DialogEditarEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbResponsable;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
