/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.historialequipos;

import java.awt.Frame;
import java.util.Map;
import modelo.MantenimientoEquipoOficina;

/**
 *
 * @author leslie
 */
public class DialogDetalleMantenimiento extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetalleMantenimiento.class.getName());
    private MantenimientoEquipoOficina mant;

    /**
     * Creates new form DialogDetalleMantenimiento
     */
    public DialogDetalleMantenimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(825,863);
    }

    DialogDetalleMantenimiento(java.awt.Frame parent, MantenimientoEquipoOficina mant) {
        super(parent, "Detalle de Mantención #" + mant.getIdMantenimientoEquipo(), true);
        initComponents();
        this.setSize(825,863);
        this.mant = mant;

        cargarDatos(mant);
        this.setLocationRelativeTo(parent);
    }

    private void cargarDatos(MantenimientoEquipoOficina mant) {
        // Campos de texto (JLabel o JTextField no editable)
        // Equipo

        System.out.println("Checklist: " + mant.getChecklist());
        System.out.println("Equipo tipo: " + mant.getEquipo().getTipoEquipo().getNombre());

        txtEquipo.setText(
                mant.getEquipo().getTipoEquipo().getNombre() + " "
                + mant.getEquipo().getMarca() + " "
                + mant.getEquipo().getModelo()
        );
        txtSerie.setText(mant.getEquipo().getNumeroSerie());

        // Mantención
        txtTipoMant.setText(mant.getTipoMantenimiento());
        txtEstado.setText(mant.getEstadoResultado());
        txtDescripcion.setText(mant.getDescripcion() != null ? mant.getDescripcion() : "Sin descripción");

        // Técnico
        txtTecnico.setText(mant.getTecnico() != null ? mant.getTecnico().getNombreUsuario() : "Sin asignar");

        // Fechas
        txtFechaRegistro.setText(mant.getFechaRegistro() != null ? mant.getFechaRegistro().toString() : "—");
        txtFechaInicio.setText(mant.getFechaInicio() != null ? mant.getFechaInicio().toString() : "—");
        txtFechaCompletado.setText(mant.getFechaCompletado() != null ? mant.getFechaCompletado().toString() : "—");

        // Piezas usadas
        txtPiezas.setText(mant.getPiezasRevisadas() != null ? mant.getPiezasRevisadas() : "—");
        // Checklist dinámico
        panelChecklist.removeAll();
        panelChecklist.setLayout(new java.awt.GridLayout(0, 2, 8, 4));

        if (mant.getChecklist() != null && !mant.getChecklist().isEmpty()) {
            for (Map.Entry<String, Boolean> item : mant.getChecklist().entrySet()) {
                javax.swing.JCheckBox chk = new javax.swing.JCheckBox(item.getKey(), item.getValue());
                chk.setEnabled(false); // solo lectura
                panelChecklist.add(chk);
            }
        } else {
            //  panelChecklist.add(new javax.swing.JLabel("Sin checklist disponible"));
        }

        // Calcular altura según cantidad de items
        int filas = (int) Math.ceil(mant.getChecklist().size() / 2.0);
        int alturaPanel = filas * 30 + 10;
        panelChecklist.setPreferredSize(new java.awt.Dimension(400, alturaPanel));
        panelChecklist.setMinimumSize(new java.awt.Dimension(400, alturaPanel));

        panelChecklist.revalidate();
        panelChecklist.repaint();
        //pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEquipo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        lblFechaRegistro = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaCompletado = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        txtTipoMant = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtTecnico = new javax.swing.JTextField();
        txtFechaRegistro = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaCompletado = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        panelChecklist = new javax.swing.JPanel();
        lblPiezas = new javax.swing.JLabel();
        txtPiezas = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEquipo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblEquipo.setText("EQUIPO");
        getContentPane().add(lblEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 81, -1, -1));

        lblSerie.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblSerie.setText("N° SERIE");
        getContentPane().add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 120, -1, -1));

        lblTipo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTipo.setText("TIPO MANTENCIÓN");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 159, -1, -1));

        lblEstado.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblEstado.setText("ESTADO");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 201, -1, -1));

        lblTecnico.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTecnico.setText("TÉCNICO");
        getContentPane().add(lblTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 243, -1, -1));

        lblFechaRegistro.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblFechaRegistro.setText("FECHA REGISTRO");
        getContentPane().add(lblFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 285, -1, -1));

        lblFechaInicio.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblFechaInicio.setText("FECHA INICIO");
        getContentPane().add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 329, -1, -1));

        lblFechaCompletado.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblFechaCompletado.setText("FECHA COMPLETADO");
        getContentPane().add(lblFechaCompletado, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 368, -1, 26));

        txtEquipo.setEditable(false);
        getContentPane().add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 78, 420, -1));

        txtSerie.setEditable(false);
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 114, 420, -1));

        txtTipoMant.setEditable(false);
        getContentPane().add(txtTipoMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 156, 420, -1));

        txtEstado.setEditable(false);
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 198, 420, -1));

        txtTecnico.setEditable(false);
        getContentPane().add(txtTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 240, 420, -1));

        txtFechaRegistro.setEditable(false);
        getContentPane().add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 282, 420, -1));

        txtFechaInicio.setEditable(false);
        getContentPane().add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 326, 420, -1));

        txtFechaCompletado.setEditable(false);
        getContentPane().add(txtFechaCompletado, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 369, 420, -1));

        lblDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDescripcion.setText("DESCRIPCIÓN");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 412, -1, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 412, 420, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("CHECK LIST:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 528, -1, -1));

        panelChecklist.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelChecklistLayout = new javax.swing.GroupLayout(panelChecklist);
        panelChecklist.setLayout(panelChecklistLayout);
        panelChecklistLayout.setHorizontalGroup(
            panelChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelChecklistLayout.setVerticalGroup(
            panelChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(panelChecklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 620, 70));

        lblPiezas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblPiezas.setText("PIEZAS USADAS");
        getContentPane().add(lblPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, -1, -1));
        getContentPane().add(txtPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 420, -1));

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 750, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("DETALLE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogDetalleMantenimiento dialog = new DialogDetalleMantenimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaCompletado;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblPiezas;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panelChecklist;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaCompletado;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtPiezas;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTecnico;
    private javax.swing.JTextField txtTipoMant;
    // End of variables declaration//GEN-END:variables
}
