/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.KilometrajeDAO;
import dao.MantenimientoDAO;
import dao.VehiculoDAO;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Kilometraje;
import modelo.Mantenimiento;
import modelo.Vehiculo;
import modelo.enums.OrigenMantenimiento;
import modelo.enums.TipoMantenimiento;

/**
 *
 * @author Jonathan Fuentealba, Gustavo Gallegos, Rodolfo Guerrero, Leslie Reyes
 */
public class DialogProgramarCorrectivo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogProgramarCorrectivo.class.getName());
    private VehiculoDAO vehiculoDAO;
    private MantenimientoDAO mantenimientoDAO;
    private KilometrajeDAO kilometrajeDAO;
    private HashMap<String, Vehiculo> mapaVehiculos;

    /**
     * Creates new form DialogProgramarCorrectivo
     */
    public DialogProgramarCorrectivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(460, 450);

        this.setLocationRelativeTo(parent);
        this.setTitle("Programar Mantenimiento Correctivo");

        // Inicializar DAO
        mantenimientoDAO = new MantenimientoDAO();
        vehiculoDAO = new VehiculoDAO();
        kilometrajeDAO = new KilometrajeDAO();
        mapaVehiculos = new HashMap<>();

        // cargar datos
        cargarComboPatentes();

    }

    private void cargarComboPatentes() {
        cmbPatente.removeAllItems();
        cmbPatente.addItem("Seleccionar");
        mapaVehiculos.clear();

        // Solo vehículos SIN mantenimiento programado actualmente
        List<Vehiculo> vehiculos = mantenimientoDAO.listarSinMantenimientoProgramado();
        for (Vehiculo v : vehiculos) {
            mapaVehiculos.put(v.getPatente(), v);  // guarda patente: vehiculo
            cmbPatente.addItem(v.getPatente());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorrectivo = new javax.swing.JLabel();
        lblPatenteC = new javax.swing.JLabel();
        cmbPatente = new javax.swing.JComboBox();
        lblMarcaC = new javax.swing.JLabel();
        txtMarcaC = new javax.swing.JTextField();
        lblModeloC = new javax.swing.JLabel();
        txtModeloC = new javax.swing.JTextField();
        lblAnioC = new javax.swing.JLabel();
        txtAnioC = new javax.swing.JTextField();
        lblTipoC = new javax.swing.JLabel();
        txtTipoC = new javax.swing.JTextField();
        lblOrigenC = new javax.swing.JLabel();
        txtOrigenC = new javax.swing.JTextField();
        lblKmC = new javax.swing.JLabel();
        txtKmC = new javax.swing.JTextField();
        btnProgramar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 450));

        lblCorrectivo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCorrectivo.setText("PROGRAMAR MANTENIMIENTO");
        lblCorrectivo.setAlignmentX(0.5F);

        lblPatenteC.setText("PATENTE");

        cmbPatente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatenteActionPerformed(evt);
            }
        });

        lblMarcaC.setText("MARCA");

        lblModeloC.setText("MODELO");

        lblAnioC.setText("AÑO");

        lblTipoC.setText("TIPO");

        lblOrigenC.setText("ORIGEN");

        lblKmC.setText("KILOMETRAJE");

        btnProgramar.setText("PROGRAMAR");
        btnProgramar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgramarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCorrectivo)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatenteC)
                            .addComponent(lblMarcaC)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAnioC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblModeloC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTipoC)
                            .addComponent(lblOrigenC)
                            .addComponent(lblKmC))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPatente, 0, 122, Short.MAX_VALUE)
                            .addComponent(txtMarcaC)
                            .addComponent(txtModeloC)
                            .addComponent(txtAnioC)
                            .addComponent(txtTipoC)
                            .addComponent(txtOrigenC)
                            .addComponent(txtKmC))))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnProgramar)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblCorrectivo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatenteC)
                    .addComponent(cmbPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaC)
                    .addComponent(txtMarcaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloC)
                    .addComponent(txtModeloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioC)
                    .addComponent(txtAnioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoC)
                    .addComponent(txtTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigenC)
                    .addComponent(txtOrigenC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKmC)
                    .addComponent(txtKmC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProgramar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatenteActionPerformed
        // TODO add your handling code here:
        String patenteSeleccionada = (String) cmbPatente.getSelectedItem();

        if (patenteSeleccionada != null && !patenteSeleccionada.equals("Seleccionar")) {
            Vehiculo seleccionado = mapaVehiculos.get(patenteSeleccionada);
            Kilometraje ultimoRegistro = kilometrajeDAO.ultimoKmPorVehiculo(seleccionado.getIdVehiculo());

            txtMarcaC.setText(seleccionado.getMarca());
            txtModeloC.setText(seleccionado.getModelo());
            txtAnioC.setText(String.valueOf(seleccionado.getAnio()));
            
            // datos por defecto en este caso
            txtTipoC.setText("Correctivo");
            txtOrigenC.setText("Manual");
            
            // último km registrado, si no tiene, se deja el inicial
            txtKmC.setText(ultimoRegistro != null ? String.valueOf(ultimoRegistro.getKilometros()) : String.valueOf(seleccionado.getKilometrajeInicial()));

            // no editables
            txtMarcaC.setEditable(false);
            txtModeloC.setEditable(false);
            txtAnioC.setEditable(false);
            txtTipoC.setEnabled(false);
            txtOrigenC.setEnabled(false);
            txtKmC.setEditable(false);

        } else {
            // Limpiar si vuelven a "Seleccionar"
            txtMarcaC.setText("");
            txtModeloC.setText("");
            txtAnioC.setText("");
        }
    }//GEN-LAST:event_cmbPatenteActionPerformed

    private void btnProgramarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramarActionPerformed
        // TODO add your handling code here:
        String patenteSeleccionada = (String) cmbPatente.getSelectedItem();
   
        if (patenteSeleccionada == null || patenteSeleccionada.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una patente.");
            return;
        }

        try {
            Vehiculo seleccionado = mapaVehiculos.get(patenteSeleccionada);
            
            int km = Integer.parseInt(txtKmC.getText().trim());

            Mantenimiento mant = new Mantenimiento();
            mant.setVehiculo(seleccionado);
            mant.setTipoMantenimiento(TipoMantenimiento.Correctivo);
            mant.setOrigen(OrigenMantenimiento.Manual); 
            mant.setKilometraje(km);

            mantenimientoDAO.correctivo(mant);

            JOptionPane.showMessageDialog(this, "Mantenimiento programado correctamente.");
            this.dispose(); // cierra el diálogo

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El kilometraje debe ser un número válido.");
        }
    }//GEN-LAST:event_btnProgramarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogProgramarCorrectivo dialog = new DialogProgramarCorrectivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProgramar;
    private javax.swing.JComboBox cmbPatente;
    private javax.swing.JLabel lblAnioC;
    private javax.swing.JLabel lblCorrectivo;
    private javax.swing.JLabel lblKmC;
    private javax.swing.JLabel lblMarcaC;
    private javax.swing.JLabel lblModeloC;
    private javax.swing.JLabel lblOrigenC;
    private javax.swing.JLabel lblPatenteC;
    private javax.swing.JLabel lblTipoC;
    private javax.swing.JTextField txtAnioC;
    private javax.swing.JTextField txtKmC;
    private javax.swing.JTextField txtMarcaC;
    private javax.swing.JTextField txtModeloC;
    private javax.swing.JTextField txtOrigenC;
    private javax.swing.JTextField txtTipoC;
    // End of variables declaration//GEN-END:variables
}
