/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.KilometrajeDAO;
import dao.MantenimientoDAO;
import dao.UsuarioDAO;
import dao.VehiculoDAO;
import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.border.Border;
import modelo.Usuario;
import modelo.Vehiculo;

/**
 *
 * @author leslie
 */
public class DialogNuevoVehiculo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoVehiculo.class.getName());

    /**
     * Creates new form DialogNuevoVehiculo
     */
    private VehiculoDAO vehiculoDAO;
    private UsuarioDAO usuarioDAO;
    private HashMap<String, Usuario> mapaUsuarios;
    private Border bordeOriginal;
    private Color colorOriginal;

    public DialogNuevoVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(460, 550);

        bordeOriginal = txtPatenteNuevo.getBorder();
        colorOriginal = lblMensajePatente.getForeground();

        this.setLocationRelativeTo(parent);
        this.setTitle("Agregar Vehículo");

        // Inicializar DAO
        vehiculoDAO = new VehiculoDAO();
        usuarioDAO = new UsuarioDAO();
        mapaUsuarios = new HashMap<>();

        // cargar datos
        cargarComboConductores();
    }

    private void cargarComboConductores() {
        cmbAsignarNuevo.removeAllItems();
        mapaUsuarios.clear();

        cmbAsignarNuevo.addItem("Asignar");

        List<Usuario> conductores = usuarioDAO.listarConductoresSinAsignacion();
        for (Usuario u : conductores) {
            String nombre = u.getNombreUsuario();
            cmbAsignarNuevo.addItem(nombre);
            mapaUsuarios.put(nombre, u);
        }
    }

    private Border crearBordeError(Border bordeOriginal) {
        return BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.RED, 2),
                bordeOriginal
        );
    }

    //fx para validar campos no nulos
    private void validarTexto(JTextField campo, JLabel label) {
        if (campo.getText().trim().isEmpty()) {
            campo.setBorder(crearBordeError(bordeOriginal));
            label.setForeground(Color.RED);
        } else {
            campo.setBorder(bordeOriginal);
        }
    }

    //restaurar validacion
    private void restaurarValidacion() {

        // Restaurar bordes originales 
        txtPatenteNuevo.setBorder(bordeOriginal);

        // Ocultar mensajes de error
        //Color fondo = pnlContenido.getBackground();
        lblMensajePatente.setForeground(colorOriginal);

        // Restaurar la tabla completa
        //cargarTabla();

        //  Mostrar mensaje
        //JOptionPane.showMessageDialog(this, "Formulario y tabla restaurados. Mostrando todos los mantenimientos.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevo = new javax.swing.JLabel();
        lblPatenteNuevo = new javax.swing.JLabel();
        txtPatenteNuevo = new javax.swing.JTextField();
        lblMarcaNuevo = new javax.swing.JLabel();
        txtMarcaNuevo = new javax.swing.JTextField();
        lblModeloNuevo = new javax.swing.JLabel();
        txtModeloNuevo = new javax.swing.JTextField();
        lblAnioNuevo = new javax.swing.JLabel();
        txtAnioNuevo = new javax.swing.JTextField();
        lblAsignarNuevo = new javax.swing.JLabel();
        cmbAsignarNuevo = new javax.swing.JComboBox<>();
        lblKmInicialNuevo = new javax.swing.JLabel();
        txtKmInicialNuevo = new javax.swing.JTextField();
        btnAgregarNuevo = new javax.swing.JButton();
        lblMensajePatente = new javax.swing.JLabel();
        lblMensajeMarca = new javax.swing.JLabel();
        lblMensajeModelo = new javax.swing.JLabel();
        lblMensajeKmInicial = new javax.swing.JLabel();
        lblMensajeAnio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblNuevo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblNuevo.setText("NUEVO VEHÍCULO");

        lblPatenteNuevo.setText("PATENTE");

        lblMarcaNuevo.setText("MARCA");

        lblModeloNuevo.setText("MODELO");

        lblAnioNuevo.setText("AÑO");

        lblAsignarNuevo.setText("CONDUCTOR");

        cmbAsignarNuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblKmInicialNuevo.setText("KM INICIAL");

        btnAgregarNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarNuevo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAgregarNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarNuevo.setText("AGREGAR");
        btnAgregarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevoActionPerformed(evt);
            }
        });

        lblMensajePatente.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajePatente.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajePatente.setText("Campo requerido");

        lblMensajeMarca.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeMarca.setText("Campo requerido");

        lblMensajeModelo.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeModelo.setText("Campo requerido");

        lblMensajeKmInicial.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeKmInicial.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeKmInicial.setText("Campo requerido");

        lblMensajeAnio.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeAnio.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeAnio.setText("Campo requerido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatenteNuevo)
                    .addComponent(lblMarcaNuevo)
                    .addComponent(lblModeloNuevo)
                    .addComponent(lblAnioNuevo)
                    .addComponent(lblAsignarNuevo)
                    .addComponent(lblKmInicialNuevo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatenteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarcaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModeloNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnioNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbAsignarNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKmInicialNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMensajeKmInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMensajePatente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblMensajeMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(6, 6, 6))
                                        .addComponent(lblMensajeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMensajeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNuevo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatenteNuevo)
                    .addComponent(txtPatenteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblMensajePatente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMarcaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcaNuevo))
                .addGap(6, 6, 6)
                .addComponent(lblMensajeMarca)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtModeloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModeloNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnioNuevo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensajeModelo)
                        .addGap(18, 18, 18)
                        .addComponent(txtAnioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(lblMensajeAnio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbAsignarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsignarNuevo))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKmInicialNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKmInicialNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeKmInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarNuevo)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoActionPerformed
        // TODO add your handling code here:
        String patente = txtPatenteNuevo.getText().trim();
        String marca = txtMarcaNuevo.getText().trim();
        String modelo = txtModeloNuevo.getText().trim();
        String anioStr = txtAnioNuevo.getText().trim();
        String conductorSeleccionado = (String) cmbAsignarNuevo.getSelectedItem();
        String kmStr = txtKmInicialNuevo.getText().trim();

        validarTexto(txtPatenteNuevo, lblMensajePatente);
        validarTexto(txtMarcaNuevo, lblMensajeMarca);
        validarTexto(txtModeloNuevo, lblMensajeModelo);
        validarTexto(txtAnioNuevo, lblMensajeAnio);
        validarTexto(txtKmInicialNuevo, lblMensajeKmInicial);

        // Validar año
        if (anioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El año es obligatorio.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int anio;
        try {
            anio = Integer.parseInt(anioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser un número entero positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar km inicial
        if (kmStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El kilometraje inicial es obligatorio.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int kmInicial;
        try {
            kmInicial = Integer.parseInt(kmStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El kilometraje debe ser un número entero positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si no se asignó conductor
        if (conductorSeleccionado == null || conductorSeleccionado.equals("Asignar")) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea continuar sin asignar un conductor?",
                    "Sin conductor",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.NO_OPTION) {
                return;
            }
        }

        try {

            Vehiculo v = new Vehiculo();
            v.setPatente(patente);
            v.setMarca(marca);
            v.setModelo(modelo);
            v.setAnio(anio);
            v.setKilometrajeInicial(Integer.parseInt(txtKmInicialNuevo.getText().trim()));
            v.setFechaRegistro(new java.sql.Date(System.currentTimeMillis()));

            // Si seleccionó conductor, asignarlo
            if (conductorSeleccionado != null && !conductorSeleccionado.equals("Asignar")) {
                Usuario conductor = mapaUsuarios.get(conductorSeleccionado);
                v.setConductor(conductor);
            }

            boolean registrado = vehiculoDAO.registrar(v);

           restaurarValidacion();

            if (registrado) {
                JOptionPane.showMessageDialog(this, "Vehículo agregado correctamente.");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IllegalArgumentException e) {
            // errores en las reglas de negocio se muestran aca
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace(); // Imprime toda la traza del error
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogNuevoVehiculo dialog = new DialogNuevoVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevo;
    private javax.swing.JComboBox<String> cmbAsignarNuevo;
    private javax.swing.JLabel lblAnioNuevo;
    private javax.swing.JLabel lblAsignarNuevo;
    private javax.swing.JLabel lblKmInicialNuevo;
    private javax.swing.JLabel lblMarcaNuevo;
    private javax.swing.JLabel lblMensajeAnio;
    private javax.swing.JLabel lblMensajeKmInicial;
    private javax.swing.JLabel lblMensajeMarca;
    private javax.swing.JLabel lblMensajeModelo;
    private javax.swing.JLabel lblMensajePatente;
    private javax.swing.JLabel lblModeloNuevo;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblPatenteNuevo;
    private javax.swing.JTextField txtAnioNuevo;
    private javax.swing.JTextField txtKmInicialNuevo;
    private javax.swing.JTextField txtMarcaNuevo;
    private javax.swing.JTextField txtModeloNuevo;
    private javax.swing.JTextField txtPatenteNuevo;
    // End of variables declaration//GEN-END:variables
}
