/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.SoftwareDAO;
import dao.UsuarioDAO;
import java.awt.Frame;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.EquipoOficina;
import modelo.Software;
import modelo.Usuario;
import util.Sesion;

/**
 *
 * @author leslie
 */
public class DialogAgregarSoftware extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarSoftware.class.getName());
    private int idEquipo;
    private boolean confirmado = false;
    private HashMap<String, Software> mapaSoftware;
    private SoftwareDAO softwareDAO;
    private UsuarioDAO usuarioDAO;

    /**
     * Creates new form DialogAgregarSoftware
     */
    public DialogAgregarSoftware(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        EstiloHirata.aplicar(getContentPane());
        this.setLocationRelativeTo(parent);
        softwareDAO = new SoftwareDAO();
        usuarioDAO = new UsuarioDAO();
        mapaSoftware = new HashMap<>();
    }

    public DialogAgregarSoftware(Frame parent, boolean modal, EquipoOficina equipo) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);

        // Inicializar DAO
        softwareDAO = new SoftwareDAO();
        mapaSoftware = new HashMap<>();
        usuarioDAO = new UsuarioDAO();

        this.idEquipo = equipo.getIdEquipo();

        // 1. Autocargar nombre del equipo (txtEquipo no editable)
        txtEquipo.setText(
                equipo.getMarca() + " "
                + equipo.getModelo() + " ("
                + equipo.getNumeroSerie() + ")"
        );
        txtEquipo.setEditable(false);

        cargarCombos(equipo.getTipoEquipo().getIdTipoEquipo());

        Usuario user = Sesion.getUsuarioActivo();
        Usuario tecnico = usuarioDAO.obtenerPorId(user.getIdUsuario());

        if (tecnico != null) {
            cmbTecnico.addItem(tecnico.getNombreUsuario());
            cmbTecnico.setSelectedItem(tecnico.getNombreUsuario());
            cmbTecnico.setEnabled(false);
        }

    }

    private void cargarCombos(int idTipoEquipo) {
        cmbSoftware.removeAllItems();
        mapaSoftware.clear();
        cmbSoftware.addItem("Seleccionar");

        List<Software> lista = softwareDAO.listarCompatiblesPorTipoEquipo(idTipoEquipo);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay software registrado para este tipo de equipo.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Software s : lista) {
            String key = s.getNombre();
            cmbSoftware.addItem(key);
            mapaSoftware.put(key, s);
        }
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEquipo = new javax.swing.JLabel();
        lblSoftware = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        cmbSoftware = new javax.swing.JComboBox<>();
        txtVersion = new javax.swing.JTextField();
        cmbTecnico = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneNotas = new javax.swing.JTextPane();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR SOFTWARE EQUIPO");

        lblEquipo.setText("EQUIPO");

        lblSoftware.setText("SOFTWARE");

        lblVersion.setText("VERSIÓN");

        lblTecnico.setText("TÉCNICO");

        lblNotas.setText("NOTAS");

        txtEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipoActionPerformed(evt);
            }
        });

        cmbSoftware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(paneNotas);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEquipo)
                            .addComponent(lblSoftware)
                            .addComponent(lblVersion)
                            .addComponent(lblTecnico)
                            .addComponent(lblNotas))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(btnGuardar))
                            .addComponent(txtEquipo)
                            .addComponent(cmbSoftware, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVersion)
                            .addComponent(cmbTecnico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(lblEquipo))
                    .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoftware)
                    .addComponent(cmbSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVersion)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTecnico)
                    .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String swSeleccionado = (String) cmbSoftware.getSelectedItem();
        String version = txtVersion.getText().trim();

        if (swSeleccionado == null || swSeleccionado.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Selecciona un software.");
            return;
        }
        if (version.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la versión.");
            return;
        }

        Software sw = mapaSoftware.get(swSeleccionado);
        Usuario tecnico = Sesion.getUsuarioActivo();

        // Verificar si ya está instalado
        if (softwareDAO.existeInstalacion(idEquipo, sw.getIdSoftware())) {
            JOptionPane.showMessageDialog(this,
                    "'" + sw.getNombre() + "' ya está instalado en este equipo.\n"
                    + "Para actualizar la versión, use el botón 'Actualizar Versión'.",
                    "Software ya instalado",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean ok = softwareDAO.registrarInstalacion(
                idEquipo,
                sw.getIdSoftware(),
                version,
                tecnico.getIdUsuario()
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Software agregado correctamente.");
            confirmado = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar. Intenta de nuevo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAgregarSoftware dialog = new DialogAgregarSoftware(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbSoftware;
    private javax.swing.JComboBox<String> cmbTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblSoftware;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JTextPane paneNotas;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
