/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.SoftwareDAO;
import dao.UsuarioDAO;
import java.awt.Frame;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelo.Usuario;
import util.Sesion;

/**
 *
 * @author leslie
 */
public class DialogActualizarVersion extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogActualizarVersion.class.getName());

    private int idSwEquipo;
    private boolean confirmado = false;
    private SoftwareDAO softwareDAO;
    private UsuarioDAO usuarioDAO;

    /**
     * Creates new form DialogActualizarVersion
     */
    public DialogActualizarVersion(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        EstiloHirata.aplicar(getContentPane());
        this.setLocationRelativeTo(parent);
        softwareDAO = new SoftwareDAO();
        usuarioDAO = new UsuarioDAO();
    }

    public DialogActualizarVersion(java.awt.Frame parent, boolean modal, int idSwEquipo, String nombreSoftware, String versionActual) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);

        softwareDAO = new SoftwareDAO();
        usuarioDAO = new UsuarioDAO();

        this.idSwEquipo = idSwEquipo;

        // Autocargar datos
        txtSoftware.setText(nombreSoftware);
        txtSoftware.setEditable(false);

        txtAnterior.setText(versionActual);
        txtAnterior.setEditable(false);

        // Técnico de sesión
        Usuario user = Sesion.getUsuarioActivo();
        Usuario tecnico = usuarioDAO.obtenerPorId(user.getIdUsuario());

        if (tecnico != null) {
            cmbTecnico.addItem(tecnico.getNombreUsuario());
            cmbTecnico.setSelectedItem(tecnico.getNombreUsuario());
            cmbTecnico.setEnabled(false);
        }
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoftware = new javax.swing.JTextField();
        txtAnterior = new javax.swing.JTextField();
        txtNueva = new javax.swing.JTextField();
        cmbTecnico = new javax.swing.JComboBox<>();
        txtNotas = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR VERSIÓN");

        jLabel2.setText("SOFTWARE");

        jLabel3.setText("VERSIÓN ACTUAL");

        jLabel4.setText("NUEVA VERSIÓN");

        jLabel5.setText("TÉCNICO");

        jLabel6.setText("NOTAS");

        txtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnteriorActionPerformed(evt);
            }
        });

        cmbTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSoftware)
                        .addComponent(txtAnterior)
                        .addComponent(txtNueva)
                        .addComponent(cmbTecnico, 0, 252, Short.MAX_VALUE)
                        .addComponent(txtNotas)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel2))
                                    .addComponent(txtSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3))
                            .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnteriorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nuevaVersion = txtNueva.getText().trim();
        String notas = txtNotas.getText().trim();

        if (nuevaVersion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la nueva versión.");
            return;
        }

        // Que la nueva versión sea distinta a la actual
        if (nuevaVersion.equals(txtAnterior.getText().trim())) {
            JOptionPane.showMessageDialog(this,
                    "La nueva versión debe ser distinta a la actual.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idTecnico = Sesion.getUsuarioActivo().getIdUsuario();

        boolean ok = softwareDAO.actualizarVersion(idSwEquipo, nuevaVersion, idTecnico, notas);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Versión actualizada correctamente.");
            confirmado = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar. Intenta de nuevo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogActualizarVersion dialog = new DialogActualizarVersion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAnterior;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtNueva;
    private javax.swing.JTextField txtSoftware;
    // End of variables declaration//GEN-END:variables
}
