/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.UsuarioDAO;
import java.awt.Color;
import java.text.Normalizer;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import modelo.Rol;
import modelo.Usuario;

/**
 *
 * @author leslie
 */
public class DialogAgregarConductor extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarConductor.class.getName());

    /**
     * Creates new form DialogAgregarConductor
     */
    private Border bordeOriginal;
    private Color colorOriginal;
    private UsuarioDAO usuarioDAO;

    public DialogAgregarConductor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(496, 374);

        bordeOriginal = txtNombreConductor.getBorder();
        colorOriginal = lblMensajeCorreo.getForeground();

        this.setLocationRelativeTo(parent);
        this.setTitle("Conductores");

        // Inicializar DAO
        usuarioDAO = new UsuarioDAO();
    }

    private Border crearBordeError(Border bordeOriginal) {
        return BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.RED, 2),
                bordeOriginal
        );
    }

    //fx para validar campos no nulos
    private void validarTexto(JTextField campo, JLabel label) {
        if (campo.getText().trim().isEmpty()) {
            campo.setBorder(crearBordeError(bordeOriginal));
            label.setForeground(Color.RED);
        } else {
            campo.setBorder(bordeOriginal);
            label.setForeground(colorOriginal);
        }
    }

    //restaurar validacion
    private void restaurarValidacion() {

        // Restaurar bordes originales 
        txtNombreConductor.setBorder(bordeOriginal);

        // Ocultar mensajes de error
        lblMensajeNombre.setForeground(colorOriginal);
    }

    private String normalizarTexto(String texto) {
        return Normalizer.normalize(texto, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .toLowerCase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDialogConductor = new javax.swing.JLabel();
        lblNombreConductor = new javax.swing.JLabel();
        txtNombreConductor = new javax.swing.JTextField();
        lblMensajeNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblMensajeCorreo = new javax.swing.JLabel();
        btnAgregarConductor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDialogConductor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDialogConductor.setText("NUEVO CONDUCTOR");
        getContentPane().add(lblDialogConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblNombreConductor.setText("NOMBRE");
        getContentPane().add(lblNombreConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        getContentPane().add(txtNombreConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, -1));

        lblMensajeNombre.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeNombre.setText("Campo requerido");
        getContentPane().add(lblMensajeNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        lblCorreo.setText("CORREO");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, -1));

        lblMensajeCorreo.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMensajeCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblMensajeCorreo.setText("Campo requerido");
        getContentPane().add(lblMensajeCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, -1));

        btnAgregarConductor.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarConductor.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAgregarConductor.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarConductor.setText("AGREGAR");
        btnAgregarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConductorActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreConductor.getText().trim();
        String correo = txtCorreo.getText().trim();

        validarTexto(txtNombreConductor, lblMensajeNombre);
        validarTexto(txtCorreo, lblMensajeCorreo);

        // Detener si hay campos vacíos
        if (nombre.isEmpty() || correo.isEmpty()) {
            return;
        }

        try {

            List<Usuario> usuarios = usuarioDAO.listarConductores();

            for (Usuario existente : usuarios) {
                // Verificar si ya existe 
                if (normalizarTexto(existente.getEmail()).equals(normalizarTexto(correo))) {
                    JOptionPane.showMessageDialog(this,
                            "Ya existe un conductor con el correo: " + correo + " (ID: " + existente.getIdUsuario() + ")",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Rol rol = new Rol();
            rol.setIdRol(3);
            rol.setNombreRol("Conductor");

            Usuario conductor = new Usuario();
            conductor.setNombreUsuario(nombre);
            conductor.setEmail(correo);
            conductor.setPassword("1234");
            conductor.setRol(rol);

            boolean registrado = usuarioDAO.insertar(conductor);

            restaurarValidacion();
            
            if (registrado) {
                JOptionPane.showMessageDialog(this, "Conductor agregado correctamente.");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el conductor.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IllegalArgumentException e) {
            // errores en las reglas de negocio se muestran aca
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace(); // Imprime toda la traza del error
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarConductorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAgregarConductor dialog = new DialogAgregarConductor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConductor;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDialogConductor;
    private javax.swing.JLabel lblMensajeCorreo;
    private javax.swing.JLabel lblMensajeNombre;
    private javax.swing.JLabel lblNombreConductor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreConductor;
    // End of variables declaration//GEN-END:variables
}
