/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dao.KilometrajeDAO;
import dao.VehiculoDAO;
import java.awt.Frame;
import javax.swing.JOptionPane;
import modelo.Kilometraje;
import modelo.Vehiculo;

/**
 *
 * @author leslie
 */
public class DialogActualizarVehiculo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogActualizarVehiculo.class.getName());

    /**
     * Creates new form DialogActualizarVehiculo
     */
    private VehiculoDAO vehiculoDAO;
    private KilometrajeDAO kilometrajeDAO;
    private Vehiculo vehiculo;

    public DialogActualizarVehiculo(Frame parent, boolean modal, Vehiculo vehiculo) {
        super(parent, modal);
        this.vehiculo = vehiculo;
        initComponents();
        this.setSize(460, 450);

        this.setLocationRelativeTo(parent);
        this.setTitle("Actualizar Vehículo");

        vehiculoDAO = new VehiculoDAO();
        kilometrajeDAO = new KilometrajeDAO();
        cargarDatos();
    }

    private void cargarDatos() {
        if (vehiculo == null) {
            return;
        }

        txtPatenteAct.setText(vehiculo.getPatente());
        txtMarcaAct.setText(vehiculo.getMarca());
        txtModeloAct.setText(vehiculo.getModelo());
        txtAnioAct.setText(String.valueOf(vehiculo.getAnio()));
        txtKmInicialAct.setText(String.valueOf(vehiculo.getKilometrajeInicial()));

        // Verificar si ya tiene registros de kilometraje
        Kilometraje ultimoKm = kilometrajeDAO.ultimoKmPorVehiculo(vehiculo.getIdVehiculo());

        if (ultimoKm != null) {
            txtKmInicialAct.setEditable(false);
            txtKmInicialAct.setToolTipText("No se puede modificar, el vehículo ya tiene registros de kilometraje");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActualizaFlota = new javax.swing.JLabel();
        lblPatenteAct = new javax.swing.JLabel();
        txtPatenteAct = new javax.swing.JTextField();
        lblMarcaAct = new javax.swing.JLabel();
        txtMarcaAct = new javax.swing.JTextField();
        lblModeloAct = new javax.swing.JLabel();
        txtModeloAct = new javax.swing.JTextField();
        lblAnioAct = new javax.swing.JLabel();
        txtAnioAct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtKmInicialAct = new javax.swing.JTextField();
        btnAct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 450));

        lblActualizaFlota.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblActualizaFlota.setText("ACTUALIZAR VEHÍCULO");

        lblPatenteAct.setText("PATENTE");

        lblMarcaAct.setText("MARCA");

        lblModeloAct.setText("MODELO");

        lblAnioAct.setText("AÑO");

        jLabel1.setText("KM INICIAL");

        btnAct.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnAct.setText("ACTUALIZAR");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblActualizaFlota))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatenteAct)
                            .addComponent(lblMarcaAct)
                            .addComponent(lblModeloAct)
                            .addComponent(lblAnioAct)
                            .addComponent(jLabel1))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAct)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPatenteAct)
                                .addComponent(txtMarcaAct)
                                .addComponent(txtModeloAct)
                                .addComponent(txtAnioAct)
                                .addComponent(txtKmInicialAct, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblActualizaFlota)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPatenteAct)
                    .addComponent(txtPatenteAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaAct)
                    .addComponent(txtMarcaAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloAct)
                    .addComponent(txtModeloAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioAct)
                    .addComponent(txtAnioAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKmInicialAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAct)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        // TODO add your handling code here:
        try {
            vehiculo.setPatente(txtPatenteAct.getText());
            vehiculo.setMarca(txtMarcaAct.getText());
            vehiculo.setModelo(txtModeloAct.getText());
            vehiculo.setAnio(Integer.parseInt(txtAnioAct.getText()));
            vehiculo.setKilometrajeInicial(Integer.parseInt(txtKmInicialAct.getText()));

            boolean actualizado = vehiculoDAO.actualizar(vehiculo);

            if (actualizado) {
                JOptionPane.showMessageDialog(this,
                        "Vehículo actualizado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                dispose(); // cerrar el dialog
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el vehículo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El año y kilometraje deben ser números válidos.",
                    "Error de formato",
                    JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogActualizarVehiculo dialog = new DialogActualizarVehiculo(
                        new javax.swing.JFrame(), true, null
                );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblActualizaFlota;
    private javax.swing.JLabel lblAnioAct;
    private javax.swing.JLabel lblMarcaAct;
    private javax.swing.JLabel lblModeloAct;
    private javax.swing.JLabel lblPatenteAct;
    private javax.swing.JTextField txtAnioAct;
    private javax.swing.JTextField txtKmInicialAct;
    private javax.swing.JTextField txtMarcaAct;
    private javax.swing.JTextField txtModeloAct;
    private javax.swing.JTextField txtPatenteAct;
    // End of variables declaration//GEN-END:variables
}
