/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author gustavo
 */
public class VistaLogin extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public VistaLogin() {
        initComponents();
        
        this.setSize(1000, 650);

        // Evita que el usuario cambie el tamaño de la ventana
        this.setResizable(false);

        // Centra la ventana en la pantalla
        this.setLocationRelativeTo(null);
        
        this.setTitle("Acceso al Sistema");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPrincipal = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jHeader = new javax.swing.JPanel();
        extBtn = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jSseparadorUser = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        jSeparadorPas = new javax.swing.JSeparator();
        jPassTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        PnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PnlPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        PnlPrincipal.setToolTipText("");
        PnlPrincipal.setMaximumSize(new java.awt.Dimension(600, 450));
        PnlPrincipal.setMinimumSize(new java.awt.Dimension(600, 450));
        PnlPrincipal.setPreferredSize(new java.awt.Dimension(600, 450));
        PnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg.setBackground(new java.awt.Color(250, 250, 250));
        lblImg.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SideIMG.png"))); // NOI18N
        lblImg.setToolTipText("");
        lblImg.setAutoscrolls(true);
        PnlPrincipal.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 580, 650));

        jHeader.setBackground(new java.awt.Color(255, 255, 255));
        jHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jHeaderMouseDragged(evt);
            }
        });
        jHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHeaderMousePressed(evt);
            }
        });

        extBtn.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(0, 0, 0));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setPreferredSize(new java.awt.Dimension(40, 40));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extBtnLayout = new javax.swing.GroupLayout(extBtn);
        extBtn.setLayout(extBtnLayout);
        extBtnLayout.setHorizontalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
            .addGroup(extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(extBtnLayout.createSequentialGroup()
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 966, Short.MAX_VALUE)))
        );
        extBtnLayout.setVerticalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jHeaderLayout = new javax.swing.GroupLayout(jHeader);
        jHeader.setLayout(jHeaderLayout);
        jHeaderLayout.setHorizontalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
            .addGroup(jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(extBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jHeaderLayout.setVerticalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(extBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnlPrincipal.add(jHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("INICIAR SESIÓN");
        PnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 350, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("Usuario");
        lblUsuario.setMaximumSize(new java.awt.Dimension(100, 20));
        lblUsuario.setPreferredSize(new java.awt.Dimension(100, 20));
        PnlPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 125, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.setMaximumSize(new java.awt.Dimension(200, 30));
        txtUsuario.setMinimumSize(new java.awt.Dimension(200, 30));
        txtUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PnlPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 360, 20));

        btnIngresar.setBackground(new java.awt.Color(0, 102, 204));
        btnIngresar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INICIAR SESIÓN");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setMaximumSize(new java.awt.Dimension(150, 40));
        btnIngresar.setMinimumSize(new java.awt.Dimension(150, 40));
        btnIngresar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        PnlPrincipal.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, 35));

        jSseparadorUser.setForeground(new java.awt.Color(0, 0, 0));
        PnlPrincipal.add(jSseparadorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 313, 360, 10));

        lblPass.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 0, 0));
        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPass.setText("Contraseña");
        lblPass.setMaximumSize(new java.awt.Dimension(100, 20));
        lblPass.setPreferredSize(new java.awt.Dimension(100, 20));
        PnlPrincipal.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 125, -1));

        jSeparadorPas.setForeground(new java.awt.Color(0, 0, 0));
        PnlPrincipal.add(jSeparadorPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 360, 10));

        jPassTxt.setBackground(new java.awt.Color(255, 255, 255));
        jPassTxt.setBorder(null);
        jPassTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPassTxtMousePressed(evt);
            }
        });
        jPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassTxtActionPerformed(evt);
            }
        });
        PnlPrincipal.add(jPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        
        //Capturamos datos ingresados por el usuario
        String emailUser = txtUsuario.getText().trim();
        String passUser = new String(jPassTxt.getPassword()).trim();
        
        dao.UsuarioDAO daoUsuario = new dao.UsuarioDAO();
        modelo.Usuario usuario = daoUsuario.verificarCredenciales(emailUser, passUser );
        
        if (usuario != null) {
            // Guardamos el usuario en la sesión
            util.Sesion.setUsuarioActivo(usuario);

            javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido " + usuario.getEmail());

            // Redirigir según el rol que devolvió la BD
            switch (usuario.getRol().getNombreRol()) {
                case "Administrador de Flota":
                    new VistaAdminFlota().setVisible(true);
                    break;
                case "Administrador de Mantenimiento":
                    new VistaAdminMantenimiento().setVisible(true);
                    break;
                case "Conductor":
                    new VistaConductor().setVisible(true);
                    break;
                default:
                    javax.swing.JOptionPane.showMessageDialog(this, "Rol no reconocido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
            }

            this.dispose(); // Cierra la ventana de Login

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Credenciales incorrectas.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassTxtActionPerformed

    private void jHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jHeaderMousePressed

    private void jHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jHeaderMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (txtUsuario.getText().equals("Ingrese su nombre de usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jPassTxt.getPassword()).isEmpty()){
            jPassTxt.setText("********");
            jPassTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jPassTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassTxtMousePressed
        if (String.valueOf(jPassTxt.getPassword()).equals("********")){
            jPassTxt.setText("");
            jPassTxt.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingrese su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_jPassTxtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlPrincipal;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel extBtn;
    private javax.swing.JPanel jHeader;
    private javax.swing.JPasswordField jPassTxt;
    private javax.swing.JSeparator jSeparadorPas;
    private javax.swing.JSeparator jSseparadorUser;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
