/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.KilometrajeDAO;
import dao.MantenimientoDAO;
import dao.VehiculoDAO;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Kilometraje;
import modelo.Mantenimiento;
import modelo.Usuario;
import modelo.Vehiculo;
import util.Sesion;

/**
 *
 * @author gustavo
 */
public class VistaConductor extends javax.swing.JFrame {

    private VehiculoDAO vehiculoDAO = new VehiculoDAO();
    private KilometrajeDAO kilometrajeDAO = new KilometrajeDAO();
    private MantenimientoDAO mantenimientoDAO = new MantenimientoDAO();

    private Vehiculo vehiculo;
    private Kilometraje ultimo;

    /**
     * Creates new form VistaConductor
     */
    public VistaConductor() {
        initComponents();

        //campos no editables
        bloquearCampos();

        this.setSize(1000, 650);

        // Evita que el usuario cambie el tamaño de la ventana
        this.setResizable(false);

        // Centra la ventana en la pantalla
        this.setLocationRelativeTo(null);

        this.setTitle("Conductor Designado");

        //cargar datos conductor
        cargarDatos();
    }

    private void bloquearCampos() {
        JTextField[] campos = {txtAnio, txtMarca, txtModelo, txtPatente, txtAnio, txtKilometroI, txtKmUltimoRegistrado, txtFechaUltimoKm};
        for (JTextField campo : campos) {
            campo.setEditable(false);
            campo.setFocusable(false);
        }
    }

    private void cargarDatos() {
        Usuario conductorLogueado = Sesion.getUsuarioActivo();
        vehiculo = vehiculoDAO.obtenerVehiculoPorConductor(conductorLogueado.getIdUsuario());

        if (vehiculo != null) {
            ultimo = kilometrajeDAO.ultimoKmPorVehiculo(vehiculo.getIdVehiculo());

            txtAnio.setText(vehiculo.getPatente());
            txtMarca.setText(vehiculo.getMarca());
            txtModelo.setText(vehiculo.getModelo());
            txtPatente.setText(vehiculo.getPatente());
            txtAnio.setText(String.valueOf(vehiculo.getAnio()));
            txtKilometroI.setText(String.valueOf(vehiculo.getKilometrajeInicial()));

            txtKmUltimoRegistrado.setText(ultimo != null ? String.valueOf(ultimo.getKilometros()) : "Sin registro");
            txtFechaUltimoKm.setText(ultimo != null ? ultimo.getFechaRegistro().toString() : "Sin registro");

        } else {
            // Si el conductor no tiene vehículo asignado
            txtAnio.setText("Sin vehículo asignado");
            txtMarca.setText("-");
            txtModelo.setText("-");
            txtPatente.setText("-");
            txtAnio.setText("-");
            txtKilometroI.setText("-");
            txtKmUltimoRegistrado.setText("-");
            txtFechaUltimoKm.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        lblKmUltimoRegistro = new javax.swing.JLabel();
        txtKilometroI = new javax.swing.JTextField();
        txtFechaUltimoKm = new javax.swing.JTextField();
        lblKilometroF = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblKilometroI1 = new javax.swing.JLabel();
        txtNuevoKm = new javax.swing.JTextField();
        lblKmUltimoRegistro1 = new javax.swing.JLabel();
        txtKmUltimoRegistrado = new javax.swing.JTextField();
        lblPatente = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(600, 450));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(600, 450));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(600, 450));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        lblInfo.setText("Información del Conductor");
        pnlPrincipal.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");
        pnlPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtNombre.setMaximumSize(new java.awt.Dimension(80, 23));
        txtNombre.setPreferredSize(new java.awt.Dimension(220, 23));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        txtMarca.setMaximumSize(new java.awt.Dimension(80, 23));
        txtMarca.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lblMarca.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMarca.setText("Marca");
        pnlPrincipal.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblModelo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblModelo.setText("Modelo");
        pnlPrincipal.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblAnio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAnio.setText("Año");
        pnlPrincipal.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtModelo.setMaximumSize(new java.awt.Dimension(80, 23));
        txtModelo.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        txtAnio.setMaximumSize(new java.awt.Dimension(80, 23));
        txtAnio.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        lblKmUltimoRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblKmUltimoRegistro.setText("Fecha ultimo registro´");
        pnlPrincipal.add(lblKmUltimoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        txtKilometroI.setMaximumSize(new java.awt.Dimension(80, 23));
        txtKilometroI.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtKilometroI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        txtFechaUltimoKm.setMaximumSize(new java.awt.Dimension(80, 23));
        txtFechaUltimoKm.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtFechaUltimoKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        lblKilometroF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblKilometroF.setText("Kilómetro Final");
        pnlPrincipal.add(lblKilometroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        btnEnviar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 180, 40));

        lblKilometroI1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblKilometroI1.setText("Kilómetro Inicial");
        pnlPrincipal.add(lblKilometroI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtNuevoKm.setMaximumSize(new java.awt.Dimension(80, 23));
        txtNuevoKm.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtNuevoKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        lblKmUltimoRegistro1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblKmUltimoRegistro1.setText("último km registrado");
        pnlPrincipal.add(lblKmUltimoRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtKmUltimoRegistrado.setMaximumSize(new java.awt.Dimension(80, 23));
        txtKmUltimoRegistrado.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtKmUltimoRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        lblPatente.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPatente.setText("Patente");
        pnlPrincipal.add(lblPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtPatente.setMaximumSize(new java.awt.Dimension(80, 23));
        txtPatente.setPreferredSize(new java.awt.Dimension(220, 23));
        pnlPrincipal.add(txtPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jButton1.setText("CERRAR SESIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        try {

            int kmNuevo = Integer.parseInt(txtNuevoKm.getText().trim());

            //  km de referencia 
            int kmUltimoRegistrado = (ultimo != null) ? ultimo.getKilometros() : vehiculo.getKilometrajeInicial();
            if (kmNuevo <= kmUltimoRegistrado) {
                JOptionPane.showMessageDialog(this,
                        "El km ingresado debe ser mayor al último registrado (" + kmUltimoRegistrado + " km).",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verificar si tiene mantenimiento programado
            if (mantenimientoDAO.tieneMantenimientoProgramado(vehiculo.getIdVehiculo())) {
                JOptionPane.showMessageDialog(this,
                        "No puedes registrar km. El vehículo tiene un mantenimiento programado pendiente.",
                        "Mantenimiento Pendiente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // nuevo kilometraje
            Kilometraje nuevoKm = new Kilometraje();
            nuevoKm.setConductor(Sesion.getUsuarioActivo());
            nuevoKm.setVehiculo(vehiculo);
            nuevoKm.setKilometros(kmNuevo);

            boolean insertado = kilometrajeDAO.insertarKilometraje(nuevoKm);

            if (insertado) {
                // PROGRAMAR MANTENIMIENTO Y ALERTA
                // referencia para el delta es el km del último mantenimiento, o el inicial si no hay
                Integer kmUltimoMant = mantenimientoDAO.obtenerKmUltimoMantenimiento(vehiculo.getIdVehiculo());
                int kmReferenciaMant = (kmUltimoMant != null) ? kmUltimoMant : vehiculo.getKilometrajeInicial();

                int diferencia = kmNuevo - kmReferenciaMant;

                if (diferencia >= 5000) {
                    // Insertar mantenimiento
                    Mantenimiento mant = new Mantenimiento();
                    mant.setVehiculo(vehiculo);
                    mant.setKilometraje(kmNuevo);
                    mantenimientoDAO.programar(mant);

                    JOptionPane.showMessageDialog(this,
                            "Km registrado. Se ha programado un mantenimiento preventivo automáticamente.",
                            "Mantenimiento Programado", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Km registrado correctamente.",
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }

                //  Refrescar datos 
                cargarDatos();
                txtNuevoKm.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Ingresa un número válido.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            util.Sesion.cerrarSesion(); // limpiar sesión
            new VistaLogin().setVisible(true); // abrir login
            this.dispose(); // cerrar vista actual
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKilometroF;
    private javax.swing.JLabel lblKilometroI1;
    private javax.swing.JLabel lblKmUltimoRegistro;
    private javax.swing.JLabel lblKmUltimoRegistro1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtFechaUltimoKm;
    private javax.swing.JTextField txtKilometroI;
    private javax.swing.JTextField txtKmUltimoRegistrado;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevoKm;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
